// Pure renderer: grounded advisory report -> branded HTML email + subject.
// Email-safe inline styles, brand tokens (ink #0B0D12, gold #D4A845/#B8893A,
// hairline #E6E8EC, signal green #2E6B4A). No data is computed here — it renders
// the already-verified report. Pure => unit-tested (report-email.test.ts).
import type { MetricsPayload } from "./report-metrics.ts";

export type EmailSection = { key: string; heading: string; body: string };
export type EmailRec = { text: string; bucket: string; dollar?: number | null; deadline?: string | null };

export type RenderInput = {
  subjectLine: string | null;
  sections: EmailSection[];
  metrics: MetricsPayload | null;
  recommendations: EmailRec[];
  coveragePct: number | null;
  periodEnd: string | null;
  model: string | null;
  businessName: string | null;
};

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const usd = (n: number) => {
  const abs = Math.abs(n);
  const d = abs < 100 && abs % 1 !== 0 ? 2 : 0;
  return (n < 0 ? "-$" : "$") + abs.toLocaleString("en-US", { minimumFractionDigits: d, maximumFractionDigits: d });
};

const fmtDate = (iso: string | null) => {
  if (!iso) return "";
  const d = new Date(iso + (iso.length === 10 ? "T00:00:00" : ""));
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
};

const BUCKET: Record<string, string> = { find_cash: "Find cash", keep_more: "Keep more", earn_new: "Earn new" };

function moneyRecoveryHtml(m: MetricsPayload): string {
  if (!m.waste.length && !m.duplicates.length && !m.costCreep.length) return "";
  const rows: string[] = [];
  for (const w of m.waste) rows.push(`<tr><td style="padding:6px 0;font-size:14px;color:#0B0D12">Dormant: <strong>${esc(w.merchant)}</strong></td><td style="padding:6px 0;text-align:right;font-size:14px;color:#2E6B4A">${usd(w.annual)}/yr</td></tr>`);
  for (const d of m.duplicates) rows.push(`<tr><td style="padding:6px 0;font-size:14px;color:#0B0D12">Duplicate: <strong>${esc(d.merchant)}</strong> — dispute by ${fmtDate(d.disputeBy)}</td><td style="padding:6px 0;text-align:right;font-size:14px;color:#2E6B4A">${usd(d.amount)} back</td></tr>`);
  for (const c of m.costCreep) rows.push(`<tr><td style="padding:6px 0;font-size:14px;color:#0B0D12">Cost creep: <strong>${esc(c.merchant)}</strong> ${usd(c.from)} → ${usd(c.to)}</td><td style="padding:6px 0;text-align:right;font-size:13px;color:#5A6170">verify</td></tr>`);
  return `<div style="border:1px solid rgba(212,168,69,.4);background:rgba(212,168,69,.06);border-radius:10px;padding:14px 18px;margin:14px 0">
    <p style="font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:#B8893A;margin:0 0 8px">Money to recover · ${usd(m.wasteAnnualTotal)}/yr identified</p>
    <table style="width:100%;border-collapse:collapse">${rows.join("")}</table></div>`;
}

function decisionsHtml(recs: EmailRec[]): string {
  if (!recs.length) return "";
  const items = recs.map((r, i) => {
    const dollar = r.dollar != null ? ` <span style="color:#2E6B4A">${usd(r.dollar)}</span>` : "";
    const by = r.deadline ? ` <span style="color:#8A93A3">by ${fmtDate(r.deadline)}</span>` : "";
    return `<li style="margin:0 0 12px;font-size:14.5px;line-height:1.6;color:#0B0D12">${esc(r.text)}<br><span style="font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:#B8893A">${esc(BUCKET[r.bucket] ?? r.bucket)}</span>${dollar}${by}</li>`;
  }).join("");
  return `<h3 style="font-size:17px;font-weight:400;color:#0B0D12;margin:24px 0 8px">What to do now</h3><ol style="margin:0;padding-left:20px">${items}</ol>`;
}

export function renderReportEmail(input: RenderInput): { subject: string; html: string } {
  const subject = input.subjectLine?.trim() || `${input.businessName ?? "Your business"}: your advisory report`;
  const blocks = input.sections.map((s) => {
    const emphasis = s.key === "verdict";
    const headStyle = emphasis ? "font-size:21px;color:#0B0D12;margin:0 0 6px" : "font-size:16px;color:#0B0D12;margin:0 0 6px";
    const extra = s.key === "leaking" && input.metrics ? moneyRecoveryHtml(input.metrics) : "";
    return `<div style="border:1px solid #E6E8EC;border-radius:12px;padding:18px 20px;margin:0 0 14px${emphasis ? ";box-shadow:0 0 0 1px rgba(212,168,69,.25)" : ""}">
      <h3 style="font-weight:400;${headStyle}">${esc(s.heading)}</h3>
      <p style="font-size:14.5px;line-height:1.7;color:#3A4150;margin:0;white-space:pre-line">${esc(s.body)}</p>${extra}</div>`;
  }).join("");

  const stamp = `Based on ${input.coveragePct != null ? `${input.coveragePct}% of transactions categorized` : "your connected accounts"}, reconciled as of ${fmtDate(input.periodEnd)}. No figures were invented — every number comes from your connected data.${input.model ? ` Generated by GoldFin Desk · ${esc(input.model)}.` : ""}`;

  const html = `<!doctype html><html><body style="margin:0;background:#ffffff;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0B0D12">
  <div style="max-width:600px;margin:0 auto;padding:36px 24px">
    <p style="font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:#B8893A;margin:0 0 6px">GoldFin Desk · Bi-Weekly Advisory</p>
    ${input.subjectLine ? `<h1 style="font-size:24px;font-weight:400;line-height:1.2;color:#0B0D12;margin:0 0 20px">${esc(input.subjectLine)}</h1>` : ""}
    ${blocks}
    ${decisionsHtml(input.recommendations)}
    <hr style="border:none;border-top:1px solid #E6E8EC;margin:22px 0 14px" />
    <p style="font-size:11.5px;line-height:1.6;color:#8A93A3;margin:0">${stamp}</p>
  </div></body></html>`;

  return { subject, html };
}
