// Top-of-funnel proof: a real auto-filled sample rendered on the public
// /templates page. The same engine and grounding gate that fills a customer's
// templates produces this demo, so a prospect sees what "filled from your
// numbers" means before connecting anything.
import { useInView } from "../../how-it-works/hooks/useInView";
import FilledTemplateTable from "../../report/FilledTemplateTable";
import { fillAllTemplates } from "../../../lib/finance/productTemplates";
import {
  SAMPLE_METRICS,
  buildSampleTemplatesCsv,
  SAMPLE_TEMPLATES_FILENAME,
} from "../../../lib/finance/sampleTemplates";

const SAMPLE = fillAllTemplates(SAMPLE_METRICS);
const PREVIEW = SAMPLE.slice(0, 2);

function downloadBytes(filename: string, bytes: BlobPart, type: string) {
  const blob = new Blob([bytes], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export default function AutoFilledSamplePreview() {
  const { ref, inView } = useInView<HTMLDivElement>({ threshold: 0.15 });
  return (
    <section
      aria-labelledby="autofilled-sample-heading"
      className="relative border-b border-ink/[0.05] bg-charcoal-950"
    >
      <div
        ref={ref}
        className={`mx-auto max-w-5xl px-6 py-20 transition-all duration-700 ease-cinema lg:px-10 ${
          inView ? "translate-y-0 opacity-100" : "translate-y-3 opacity-0"
        }`}
      >
        <div className="max-w-[60ch]">
          <div className="text-[10.5px] uppercase tracking-[0.32em] text-champagne-300/70">
            A real auto-filled sample
          </div>
          <h2
            id="autofilled-sample-heading"
            className="mt-4 font-light text-ink text-[30px] leading-[1.12] tracking-[-0.005em] sm:text-[40px]"
          >
            This is what your numbers look like, filled in
          </h2>
          <p className="mt-4 text-[15px] leading-[1.7] text-ink/65">
            Generated by the same engine that fills your real templates - every cell traceable, nothing invented.
            Download it and open it in Excel, Google Sheets, or Numbers.
          </p>
        </div>

        <div className="mt-9 grid gap-4 sm:grid-cols-2">
          {PREVIEW.map((t) => (
            <FilledTemplateTable key={t.title} t={t} />
          ))}
        </div>

        <a
          href="/downloads/goldfin-template-vault.xlsx"
          download
          className="mt-8 rounded-full border border-champagne-200/40 px-5 py-2.5 text-[13px] text-champagne-300 transition-colors duration-200 ease-cinema hover:bg-champagne-300/[0.06] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-champagne-200/50"
        >
          Download the full filled sample (.xlsx)
        </a>
        <button
          type="button"
          onClick={() => downloadBytes(SAMPLE_TEMPLATES_FILENAME, buildSampleTemplatesCsv(), "text/csv;charset=utf-8")}
          className="ml-3 mt-8 text-[12px] text-ink/45 underline-offset-4 transition-colors hover:text-champagne-300 hover:underline"
        >
          CSV fallback
        </button>
      </div>
    </section>
  );
}
