export const HIW_COPY = {
  intro: {
    eyebrow: "HOW IT WORKS",
    headline: "Your monthly finance rhythm, built for owner-led businesses.",
    sub: "GoldFin Desk turns scattered financial activity into organized spreadsheets, plain-English briefings, and a monthly review — so you can stop guessing from your bank balance. Start free, or have it done for you for $99/mo.",
    primary: "Get the free Template Vault",
    secondary: "Generate Sample Finance Briefing",
    trust: "No bank connection required to preview the experience.",
    loop: ["Bank activity", "Spreadsheet structure", "Plain-English briefing", "Monthly review"],
  },
  steps: [
    {
      n: "01",
      title: "Start with structure",
      body: "We begin with expert-built financial spreadsheet systems designed to organize your business activity into a clearer operating view.",
      proof: "Built for owners who have outgrown messy spreadsheets.",
    },
    {
      n: "02",
      title: "Connect after onboarding",
      body: "After you apply and onboard, your business bank data can be connected through Plaid so the system works from your actual financial activity.",
      proof: "No bank connection is required for the public preview.",
    },
    {
      n: "03",
      title: "Organize the financial activity",
      body: "AI assists with placing financial movement into the right spreadsheet structure, reducing manual entry and making the system easier to keep current.",
      proof: "AI is the assistant. Clarity is the outcome.",
    },
    {
      n: "04",
      title: "Receive bi-weekly plain-English briefings",
      body: "Every two weeks, you receive a readable finance briefing that explains what changed, what looks risky, and what decisions may need attention.",
      proof: "The briefing is the moment your numbers start to make sense.",
    },
    {
      n: "05",
      title: "Review monthly with strategy",
      body: "Once a month, you step out of the day-to-day and review your numbers, questions, and decisions in a focused one-hour strategy conversation.",
      proof: "Agenda: cash position, revenue quality, expense pressure, hiring readiness, next decisions.",
    },
  ],
  vs: {
    headline: "You do not need another finance project on your plate.",
    sub: "The GoldFin Desk is designed to give owners a recurring finance rhythm without making them become the finance department.",
    you: [
      "Describe your business and goals",
      "Apply for the premium desk",
      "Complete onboarding",
      "Review the briefings",
      "Join the monthly strategy call",
      "Make clearer decisions",
    ],
    desk: [
      "Builds the financial spreadsheet system",
      "Connects data after onboarding",
      "Organizes activity into structure",
      "Prepares plain-English briefings",
      "Surfaces patterns and questions",
      "Creates a monthly decision rhythm",
    ],
    cta: "See a Sample Briefing",
  },
  cycle: {
    headline: "A finance rhythm that repeats every month.",
    weeks: [
      { w: "Week 1", t: "Financial activity is organized" },
      { w: "Week 2", t: "First plain-English briefing" },
      { w: "Week 3", t: "Patterns and questions are reviewed" },
      { w: "Week 4", t: "Monthly strategy call" },
    ],
    end: "Clearer decisions for the next month.",
    line: "The value is not a one-time report. It is the discipline of never letting the financial side of the business disappear into the background.",
  },
  ba: {
    before: {
      label: "Before",
      title: "Running from the bank balance",
      bullets: [
        "Scattered bank statements",
        "Spreadsheets no one updates consistently",
        "Reports that explain what happened too late",
        "Decisions based on instinct",
        "Cash anxiety before hiring or spending",
      ],
    },
    after: {
      label: "After",
      title: "Running with a GoldFin Desk",
      bullets: [
        "Organized financial structure",
        "Bi-weekly plain-English briefings",
        "Questions surfaced before they become problems",
        "Monthly strategic review",
        "Decisions made from a clearer financial view",
      ],
    },
    line: "From reactive financial management to proactive financial visibility.",
  },
  sample: {
    headline: "What your business should be seeing every two weeks.",
    tabs: [
      {
        id: "cash",
        label: "Cash Movement",
        body: "Cash increased this period, but most of the gain came from delayed vendor payments rather than stronger operating margin.",
        rows: [
          ["Inflows", "+$92,400"],
          ["Outflows", "-$78,900"],
          ["Net change", "+$13,500"],
        ],
      },
      {
        id: "revenue",
        label: "Revenue Trend",
        body: "Revenue is growing week over week, but growth is concentrated in a small number of accounts. Review whether the trend is durable.",
        rows: [
          ["Week-over-week", "+14%"],
          ["Top 3 accounts share", "62%"],
          ["New accounts this period", "2"],
        ],
      },
      {
        id: "expense",
        label: "Expense Pattern",
        body: "Software, contractor, and payroll costs are rising faster than revenue. Review fixed commitments before adding another recurring expense.",
        rows: [
          ["Software", "+9%"],
          ["Contractors", "+12%"],
          ["Payroll", "+6%"],
        ],
      },
      {
        id: "unusual",
        label: "Unusual Spend",
        body: "Three transactions sit meaningfully above their category average and may be worth a quick second look.",
        rows: [
          ["Vendor A — software", "$4,200"],
          ["Vendor B — travel", "$2,860"],
          ["Vendor C — services", "$1,940"],
        ],
      },
      {
        id: "questions",
        label: "Questions to Review",
        body: "A short list of questions surfaced from this period's activity.",
        rows: [
          ["", "Can the business support another hire?"],
          ["", "Are contractor costs reducing margin?"],
          ["", "Is ad spend producing measurable cash flow?"],
          ["", "Should cash reserves be increased before expansion?"],
        ],
      },
      {
        id: "decisions",
        label: "Decisions to Consider",
        body: "Decisions that may deserve attention before the next cycle.",
        rows: [
          ["", "Hold hiring until margin stabilizes"],
          ["", "Renegotiate two largest software contracts"],
          ["", "Set a cash reserve floor before next expansion"],
        ],
      },
    ],
    cta: "Generate My Sample Finance Briefing",
    micro: "Use demo data or rough non-sensitive numbers. No bank connection required.",
  },
  diff: {
    headline: "More than bookkeeping. Lighter than a full CFO.",
    cols: ["What it helps with", "What it usually misses", "Best fit"],
    rows: [
      {
        name: "Bookkeeper",
        helps: "Categorizing transactions and keeping the books current.",
        misses: "Plain-English interpretation and forward-looking decisions.",
        fit: "Businesses needing accurate historical records.",
      },
      {
        name: "Dashboard",
        helps: "Real-time charts and KPI tiles pulled from connected sources.",
        misses: "Context, interpretation, and what to actually do next.",
        fit: "Teams who already know what to look for.",
      },
      {
        name: "Spreadsheet Template",
        helps: "A starting structure for organizing financial activity.",
        misses: "Recurring rhythm, interpretation, and accountability.",
        fit: "Owners willing to maintain the system themselves.",
      },
      {
        name: "Fractional CFO",
        helps: "Strategic finance leadership and modeling.",
        misses: "Lightweight pricing and a fixed monthly rhythm.",
        fit: "Companies large enough to need a finance leader.",
      },
      {
        name: "GoldFin Desk",
        helps: "Recurring financial structure, plain-English interpretation, and monthly decision rhythm.",
        misses: "Not a replacement for tax, legal, or full bookkeeping cleanup.",
        fit: "Owner-led businesses that need more clarity than tools alone provide, but are not ready for a full finance department.",
        highlight: true,
      },
    ],
    cta: "Auto-fill my reports — $99/mo",
  },
  trust: {
    headline: "Preview safely. Connect only after trust is built.",
    cards: [
      "No bank connection required for preview",
      "Use demo data or rough non-sensitive numbers",
      "Plaid connection happens after onboarding",
      "Clear process before any financial connection",
      "Built for business owners who take financial privacy seriously",
    ],
  },
  final: {
    headline: "Ready to stop guessing from your bank balance?",
    sub: "Start with the free GoldFin Template Vault and organize your numbers today — or have them filled for you every month with GoldFin Reports at $99/mo.",
    primary: "Get the free Template Vault",
    secondary: "Auto-fill my reports — $99/mo",
    tertiary: "Or apply for GoldFin Advisory",
    micro: "Free, email-only. No bank connection. Upgrade anytime.",
  },
};
