export const APPLY = {
  header: {
    brand: "GoldFin Advisory",
    label: "Application",
    secondary: "Not ready? Generate Sample Briefing",
  },
  steps: ["Fit", "Business", "Numbers", "Readiness", "Review"],
  landing: {
    eyebrow: "PRIVATE APPLICATION",
    headline: "Apply for the GoldFin Advisory",
    sub: "Tell us a little about your business, your current financial setup, and what you want to understand better. No bank connection, documents, or payment required to apply.",
    micro: "Application takes about 3 minutes. No bank connection required.",
    primary: "Start My Application",
    secondary: "Generate Sample Finance Briefing",
    tertiary: "Start with Free Templates",
    fitNote: "Best for businesses that have outgrown bank-balance guessing but are not ready for a full finance team.",
    rhythmCard: {
      title: "Your Monthly Finance Rhythm",
      items: [
        "Structured spreadsheets",
        "Bi-weekly plain-English briefing",
        "Monthly one-hour strategy review",
      ],
      price: "$1,500 / month",
      sub: "Built for owner-led businesses.",
    },
    welcomeBack: "Welcome back. Continue your GoldFin Advisory application.",
  },
  step1: {
    headline: "First, let's see if this is the right level of support.",
    sub: "The GoldFin Advisory is designed for owner-led businesses with real financial movement, recurring expenses, and decisions that need clearer numbers.",
    businessTypes: [
      "Agency",
      "Clinic",
      "Trades business",
      "Restaurant / hospitality",
      "E-commerce",
      "Professional services",
      "Local service business",
      "Consulting / advisory",
      "Creative studio",
      "Other",
    ],
    revenueRanges: [
      "Under $10K/month",
      "$10K–$30K/month",
      "$30K–$75K/month",
      "$75K–$150K/month",
      "$150K–$250K/month",
      "$250K+/month",
    ],
    lowFit: "The premium GoldFin Advisory may be more useful once your business has more recurring financial complexity. You can still apply, or start with the free templates.",
    goodFit: "This is usually where owners begin needing a recurring financial rhythm beyond basic bookkeeping.",
  },
  step2: {
    headline: "What are you currently using to understand your numbers?",
    sub: "Most owners already have tools. The gap is usually interpretation and rhythm.",
    tools: [
      "Bookkeeper",
      "CPA",
      "QuickBooks",
      "Xero",
      "Google Sheets / Excel",
      "Bank statements",
      "Stripe / Square / Shopify",
      "Gusto / payroll tool",
      "Ramp / Brex / Mercury",
      "None of these consistently",
      "Other",
    ],
    gapLabel: "What still feels unclear, even with those tools?",
    gapPlaceholder: "Example: \"Revenue is growing, but cash still feels tight. I'm not sure if we can afford another hire.\"",
    gapChips: [
      "Cash feels tight",
      "Hiring decision",
      "Expenses are rising",
      "I do not trust my reports",
      "I only check the bank balance",
      "I need better monthly review",
      "I want plain-English interpretation",
      "I am tired of spreadsheets",
    ],
    micro: "You do not need perfect financial language. Explain it the way you would to a trusted advisor.",
  },
  step3: {
    headline: "What do you want your numbers to help you decide?",
    sub: "The best-fit businesses usually have real decisions they are trying to make from unclear financial information.",
    decisions: [
      "Can I afford to hire?",
      "Should I cut expenses?",
      "Is revenue growth actually improving cash?",
      "Are payroll or contractor costs too high?",
      "Are subscriptions/software costs creeping up?",
      "Should I raise prices?",
      "How much cash should I keep reserved?",
      "Can I invest in marketing?",
      "Are we actually profitable?",
      "What should I review every month?",
    ],
    outcomeLabel: "What would financial clarity change for you?",
    outcomePlaceholder: "Example: \"I would feel more confident hiring, setting budgets, and planning the next quarter.\"",
  },
  step4: {
    headline: "Is the monthly rhythm a fit for how you want to run the business?",
    sub: "This works best for owners who want to review financials consistently, not just when something feels wrong.",
    review: {
      label: "Are you currently willing to review your numbers at least once per month?",
      options: ["Yes, that is what I need", "I want to, but I have not had a system", "Not sure yet"],
      reassureValue: "I want to, but I have not had a system",
      reassureText: "That is exactly the gap the GoldFin Advisory is designed to solve.",
    },
    budget: {
      label: "Are you comfortable with a $1,500/month premium finance subscription if it is a fit?",
      options: ["Yes", "Possibly, if I understand the value", "Not right now"],
      reassureValue: "Not right now",
      reassureText: "The free templates may be the better starting point. You can still finish the application, or start there.",
    },
    worth: {
      label: "What would make this feel worth it after the first 60 days?",
      placeholder: "Example: \"I'd want to understand cash flow better, know if hiring is safe, and stop guessing from the bank balance.\"",
    },
    timeline: {
      label: "How soon are you looking to improve financial visibility?",
      options: ["Immediately", "This month", "This quarter", "Exploring for later"],
    },
  },
  step5: {
    headline: "Review your application",
    sub: "No payment, bank connection, or document upload is required at this stage.",
    consent: "I understand this application does not require payment or bank connection.",
    submit: "Submit My Application",
    save: "Save and Finish Later",
    micro: "Application takes only a few minutes. No bank connection required.",
    trust: {
      title: "What happens after you apply",
      items: [
        "We review your business context.",
        "If there is a potential fit, you receive next steps.",
        "Bank connection only happens after onboarding.",
        "The goal is to determine whether the GoldFin Advisory can create a useful monthly finance rhythm for your business.",
      ],
    },
    loading: [
      "Reviewing your application context…",
      "Organizing your business profile…",
      "Preparing next-step summary…",
    ],
  },
  success: {
    headline: "Your application has been received.",
    sub: "Thank you for applying to the GoldFin Advisory. If your business appears to be a fit, you will receive next steps for the premium finance desk review process.",
    confirm: [
      "Application received",
      "No bank connection completed",
      "No payment collected",
      "Next step: fit review",
    ],
    timeline: [
      "Application submitted",
      "Fit review",
      "Next-step email",
      "Onboarding if accepted",
      "First finance rhythm begins",
    ],
    primary: "Generate My Sample Briefing",
    secondary: "Get the Free Templates",
    wait: [
      { t: "Download Cash Flow Forecast Template", href: "#/templates" },
      { t: "Preview Full Sample Briefing", href: "#top" },
      { t: "Read: Why Your Bank Balance Is Not a Financial Strategy", href: "#how-it-works" },
    ],
  },
  errors: {
    email: "Enter a valid work email.",
    required: "This helps us understand fit before reviewing your application.",
    revenue: "Select the range that feels closest. Exact numbers are not required.",
    text: "A short sentence is enough. You do not need perfect financial language.",
    submit: "Something prevented the application from submitting. Your answers are still here. Please try again.",
    consent: "Please confirm to submit your application.",
  },
};

export const LLOW_FIT_RANGES = new Set(["Under $10K/month", "$10K–$30K/month"]);
